version: '3.9'
services:
  online-naplo:
    build:
      context: ./backend
    container_name: online-naplo-app
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      JWT_SECRET: change-me-in-production
      NODE_ENV: production
    volumes:
      - ./database:/app/database